### ISSUE TITLE
test interactive plot

### ISSUE THREAD

**Issue by janekg89** [matthiaskoenig/pkdb_analysis#15]
test that interactive plots are created.

**Comment by matthiaskoenig** [comment]
tests are failing in travis

**Comment by matthiaskoenig** [comment]
@janekg89 Tests should always create all files in `tmp_path` fixtures. This keeps the repository clean and checks that everything works in clean directories. I.e. the test must be
```
def test_interactive_plot1(tmp_path):
    """Test plot creation.

    You can use the tmp_path fixture which will provide a
    temporary directory unique to the test invocation,
    created in the base temporary directory.
    """
    create_plots(path=tmp_path)
```
Currently the tests fail, because one cannot create the example in a clean directory. You should check if tests pass on travis: https://travis-ci.org/matthiaskoenig/pkdb_analysis

**Comment by janekg89** [comment]
yes, I believe the problem on Travis is that it cannot create the "interactive" directory on the server. Do you have a neat solution for that?

**Comment by matthiaskoenig** [comment]
No, the problem is that your paths are wrong. This is also not working locally.
